// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Consultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("PacientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PacientRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PacientId");

                    b.HasIndex("PacientRecordId");

                    b.ToTable("consultations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MedicalCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("PacientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PacientRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PacientId");

                    b.HasIndex("PacientRecordId");

                    b.ToTable("medicalConditions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PacientRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PacientRecord");
                });

            modelBuilder.Entity("Domain.Entities.Treatment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("PacientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PacientRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PacientId");

                    b.HasIndex("PacientRecordId");

                    b.ToTable("trataments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Pacient", b =>
                {
                    b.HasBaseType("Domain.Entities.User");

                    b.Property<Guid>("PacientRecordId")
                        .HasColumnType("uuid");

                    b.HasIndex("PacientRecordId");

                    b.ToTable("pacients", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Consultation", b =>
                {
                    b.HasOne("Domain.Entities.Pacient", "Pacient")
                        .WithMany()
                        .HasForeignKey("PacientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PacientRecord", null)
                        .WithMany("Consultations")
                        .HasForeignKey("PacientRecordId");

                    b.Navigation("Pacient");
                });

            modelBuilder.Entity("Domain.Entities.MedicalCondition", b =>
                {
                    b.HasOne("Domain.Entities.Pacient", "Pacient")
                        .WithMany()
                        .HasForeignKey("PacientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PacientRecord", null)
                        .WithMany("MedicalConditions")
                        .HasForeignKey("PacientRecordId");

                    b.Navigation("Pacient");
                });

            modelBuilder.Entity("Domain.Entities.Treatment", b =>
                {
                    b.HasOne("Domain.Entities.Pacient", "Pacient")
                        .WithMany()
                        .HasForeignKey("PacientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PacientRecord", null)
                        .WithMany("Treatments")
                        .HasForeignKey("PacientRecordId");

                    b.Navigation("Pacient");
                });

            modelBuilder.Entity("Domain.Entities.Pacient", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Pacient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PacientRecord", "PacientRecord")
                        .WithMany()
                        .HasForeignKey("PacientRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PacientRecord");
                });

            modelBuilder.Entity("Domain.Entities.PacientRecord", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("MedicalConditions");

                    b.Navigation("Treatments");
                });
#pragma warning restore 612, 618
        }
    }
}
